### ISSUE TITLE
unresolved import ethers::contract::Abigen, no Abigen in contract

### ISSUE THREAD

**Issue by vladimir-poopin** [gakonst/ethers-rs#1610]
**Version**
v0.17.0

**Platform**
`Darwin 192.168.0.101 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64`

**Description**
Cargo can't resolve the Abigen struct from `ethers::contract` (also tried with `ethers::prelude::*`).

I tried this code in `./build.rs`:
```rs
use ethers::contract::Abigen;

fn main() -> eyre::Result<()> {
    Abigen::new("TestContract", "./abi/TestContract.json")?.generate()?.write_to_file("./abi/test_contract.rs")?;
    Ok(())
}
```

Result from `cargo build`:
```
error[E0432]: unresolved import `ethers::contract::Abigen`
 --> build.rs:1:5
  |
1 | use ethers::contract::Abigen;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `Abigen` in `contract`
```
Tried both `ethers = "0.17.0"` and `ethers = { git = "https://github.com/gakonst/ethers-rs" }` in my `Cargo.toml`

```toml
[dependencies]
tokio = "1.20.1"
ethers = { git = "https://github.com/gakonst/ethers-rs" }
eyre = "0.6.8"

[build-dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
eyre = "0.6.8"
```

Not really sure what's going on tbh. Could be a bug, but I'm probably just doing something wrong.
