### ISSUE TITLE
rust-analyzer complains on `abigen!`

### ISSUE THREAD

**Issue by xJonathanLEI** [gakonst/ethers-rs#940]
## Version

```log
├── ethers v0.6.2
│   ├── ethers-contract v0.6.2
│   │   ├── ethers-contract-abigen v0.6.3
│   │   │   ├── ethers-core v0.6.3
│   │   ├── ethers-contract-derive v0.6.3 (proc-macro)
│   │   │   ├── ethers-contract-abigen v0.6.3
│   │   │   │   ├── ethers-core v0.6.3
│   │   │   ├── ethers-core v0.6.3 (*)
│   │   ├── ethers-core v0.6.3 (*)
│   │   ├── ethers-providers v0.6.2
│   │   │   ├── ethers-core v0.6.3 (*)
│   ├── ethers-core v0.6.3 (*)
│   ├── ethers-etherscan v0.2.2
│   │   ├── ethers-core v0.6.3 (*)
│   ├── ethers-middleware v0.6.2
│   │   ├── ethers-contract v0.6.2 (*)
│   │   ├── ethers-core v0.6.3 (*)
│   │   ├── ethers-etherscan v0.2.2 (*)
│   │   ├── ethers-providers v0.6.2 (*)
│   │   ├── ethers-signers v0.6.2
│   │   │   ├── ethers-core v0.6.3 (*)
│   ├── ethers-providers v0.6.2 (*)
│   ├── ethers-signers v0.6.2 (*)
│   └── ethers-solc v0.1.2
│       ├── ethers-core v0.6.3 (*)
```

## Platform

```log
Linux dev 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

## Description

Using the `abigen` macro results in rust-analyzer errors, which in turn make code completion unusable.

**/Cargo.toml**

```toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "=0.6.2"
serde_json = "=1.0.79"
```

**/src/main.rs**

```rs
use ethers::prelude::abigen;

abigen!(ERC20, "src/ERC20.json");

fn main() {}
```

**/src/ERC20.json**

```json
[
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
]
```

The code compiles just fine:

```bash
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
```

But rust-analyzer is not happy:

![image](https://user-images.githubusercontent.com/19556359/154958623-da8f648e-6670-4b25-bf95-d1cc9121873e.png)

Not sure if it's just me though.

**Comment by xJonathanLEI** [comment]
Tried changing to use `ethers` from GitHub (rev [3effda2](https://github.com/gakonst/ethers-rs/commit/3effda28049e9a1c67c5406e5612ddda74185879)). Still the same: code compiles but rust-analyzer yells at me.

**Comment by xJonathanLEI** [comment]
Tried using a _very_ old commit (which my old projects were locked to) and it works perfectly:

**/Cargo.toml**

```toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.45"
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "b425e2bd9ac932e208bcfe221a841d390afe6341" }
serde_json = "=1.0.79"
```

Note that `anyhow` must be locked to `1.0.45` or below as it looks like newer versions don't work with old `ethers`.
